#!/bin/bash
#git clone https://github.com/apache/accumulo.git
#git clone https://github.com/apache/activemq.git
#git clone https://github.com/apache/avro.git
#git clone https://github.com/apache/camel.git
#git clone https://github.com/apache/cassandra.git
#git clone https://github.com/apache/commons-lang.git
#git clone https://github.com/apache/cordova-android.git
#git clone https://github.com/apache/flume.git
#git clone https://github.com/apache/giraph.git
#git clone https://github.com/apache/hadoop-common.git
#git clone https://github.com/apache/hadoop-hdfs.git
#git clone https://github.com/apache/hadoop-mapreduce.git
#git clone https://github.com/apache/hbase.git
#git clone https://github.com/apache/hive.git
#git clone https://github.com/apache/incubator-drill.git
#git clone https://github.com/apache/karaf.git
#git clone https://github.com/apache/lucene-solr.git
#git clone https://github.com/apache/mahout.git
#git clone https://github.com/apache/nutch.git
#git clone https://github.com/apache/pig.git
#git clone https://github.com/apache/shiro.git
#git clone https://github.com/apache/solr.git
#git clone https://github.com/apache/struts2.git
#git clone https://github.com/apache/tika.git
#git clone https://github.com/apache/tomcat.git
#git clone https://github.com/apache/tomcat70.git
#git clone https://github.com/apache/whirr.git
#git clone https://github.com/apache/wicket.git
#git clone https://github.com/apache/zookeeper.git
#git clone https://github.com/apache/abdera.git
#git clone https://github.com/apache/ace.git
#git clone https://github.com/apache/activemq-activeio.git
#git clone https://github.com/apache/activemq-apollo.git
#git clone https://github.com/apache/activemq-protobuf.git
#git clone https://github.com/apache/ant.git
#git clone https://github.com/apache/any23.git
#git clone https://github.com/apache/archiva-sandbox.git
#git clone https://github.com/apache/archiva.git
#git clone https://github.com/apache/aries.git
#git clone https://github.com/apache/axis1.git
#git clone https://github.com/apache/axis2-java.git
#git clone https://github.com/apache/axis2-transports.git
#git clone https://github.com/apache/batik.git
#git clone https://github.com/apache/bookkeeper.git
#git clone https://github.com/apache/bval.git
#git clone https://github.com/apache/cayenne.git
#git clone https://github.com/apache/chainsaw.git
#git clone https://github.com/apache/chemistry-opencmis.git
#git clone https://github.com/apache/chemistry.git
#git clone https://github.com/apache/chukwa.git
#git clone https://github.com/apache/clerezza.git
#git clone https://github.com/apache/cloudstack.git
#git clone https://github.com/apache/cocoon.git
#git clone https://github.com/apache/commons-attributes.git
#git clone https://github.com/apache/commons-bcel.git
#git clone https://github.com/apache/commons-beanutils.git
#git clone https://github.com/apache/commons-betwixt.git
#git clone https://github.com/apache/commons-bsf.git
#git clone https://github.com/apache/commons-chain.git
#git clone https://github.com/apache/commons-cli.git
#git clone https://github.com/apache/commons-codec.git
#git clone https://github.com/apache/commons-collections.git
#git clone https://github.com/apache/commons-compress.git
#git clone https://github.com/apache/commons-configuration.git
#git clone https://github.com/apache/commons-csv.git
#git clone https://github.com/apache/commons-dbcp.git
#git clone https://github.com/apache/commons-dbutils.git
#git clone https://github.com/apache/commons-digester.git
#git clone https://github.com/apache/commons-discovery.git
#git clone https://github.com/apache/commons-el.git
#git clone https://github.com/apache/commons-email.git
#git clone https://github.com/apache/commons-exec.git
#git clone https://github.com/apache/commons-fileupload.git
#git clone https://github.com/apache/commons-functor.git
#git clone https://github.com/apache/commons-imaging.git
#git clone https://github.com/apache/commons-io.git
#git clone https://github.com/apache/commons-jci.git
#git clone https://github.com/apache/commons-jcs.git
#git clone https://github.com/apache/commons-jexl.git
#git clone https://github.com/apache/commons-jxpath.git
#git clone https://github.com/apache/commons-launcher.git
#git clone https://github.com/apache/commons-logging.git
#git clone https://github.com/apache/commons-math.git
#git clone https://github.com/apache/commons-modeler.git
#git clone https://github.com/apache/commons-net.git
#git clone https://github.com/apache/commons-ognl.git
#git clone https://github.com/apache/commons-pool.git
#git clone https://github.com/apache/commons-primitives.git
#git clone https://github.com/apache/commons-proxy.git
#git clone https://github.com/apache/commons-transaction.git
#git clone https://github.com/apache/commons-validator.git
#git clone https://github.com/apache/commons-vfs.git
#git clone https://github.com/apache/continuum.git
#git clone https://github.com/apache/creadur-rat.git
#git clone https://github.com/apache/creadur-tentacles.git
#git clone https://github.com/apache/creadur-whisker.git
#git clone https://github.com/apache/crunch.git
#git clone https://github.com/apache/cxf-dosgi.git
#git clone https://github.com/apache/cxf-fediz.git
#git clone https://github.com/apache/cxf.git
#git clone https://github.com/apache/deltaspike.git
#git clone https://github.com/apache/derby.git
#git clone https://github.com/apache/directmemory-lightning.git
#git clone https://github.com/apache/directmemory.git
#git clone https://github.com/apache/directory-clients.git
#git clone https://github.com/apache/directory-daemon.git
#git clone https://github.com/apache/directory-installers.git
#git clone https://github.com/apache/directory-samples.git
#git clone https://github.com/apache/directory-server.git
#git clone https://github.com/apache/directory-shared.git
#git clone https://github.com/apache/directory-studio-plugin.git
#git clone https://github.com/apache/directory-studio.git
#git clone https://github.com/apache/empire-db.git
#git clone https://github.com/apache/etch.git
#git clone https://github.com/apache/felix.git
#git clone https://github.com/apache/flex-falcon.git
#git clone https://github.com/apache/fop.git
#git clone https://github.com/apache/forrest.git
#git clone https://github.com/apache/ftpserver.git
#git clone https://github.com/apache/geronimo-devtools.git
#git clone https://github.com/apache/geronimo-genesis.git
#git clone https://github.com/apache/geronimo-gshell.git
#git clone https://github.com/apache/geronimo-jaspi.git
#git clone https://github.com/apache/geronimo-javamail.git
#git clone https://github.com/apache/geronimo-specs.git
#git clone https://github.com/apache/geronimo-txmanager.git
#git clone https://github.com/apache/geronimo-xbean.git
#git clone https://github.com/apache/geronimo-yoko.git
#git clone https://github.com/apache/geronimo.git
#git clone https://github.com/apache/gora.git
#git clone https://github.com/apache/hama.git
#git clone https://github.com/apache/harmony-classlib.git
#git clone https://github.com/apache/harmony-jdktools.git
#git clone https://github.com/apache/harmony.git
#git clone https://github.com/apache/hcatalog.git
#git clone https://github.com/apache/httpasyncclient.git
#git clone https://github.com/apache/httpclient.git
#git clone https://github.com/apache/httpcore.git
#git clone https://github.com/apache/incubator-ambari.git
#git clone https://github.com/apache/incubator-falcon.git
#git clone https://github.com/apache/incubator-hdt.git
#git clone https://github.com/apache/incubator-helix.git
#git clone https://github.com/apache/incubator-knox.git
#git clone https://github.com/apache/incubator-marmotta.git
#git clone https://github.com/apache/incubator-metamodel.git
#git clone https://github.com/apache/incubator-provisionr.git
#git clone https://github.com/apache/incubator-s4.git
#git clone https://github.com/apache/incubator-sentry.git
#git clone https://github.com/apache/incubator-tajo.git
#git clone https://github.com/apache/incubator-tez.git
#git clone https://github.com/apache/isis.git
#git clone https://github.com/apache/ivy.git
#git clone https://github.com/apache/ivyde.git
#git clone https://github.com/apache/jackrabbit-oak.git
#git clone https://github.com/apache/jackrabbit.git
#git clone https://github.com/apache/james-app.git
#git clone https://github.com/apache/james-hupa.git
#git clone https://github.com/apache/james-imap.git
#git clone https://github.com/apache/james-jdkim.git
#git clone https://github.com/apache/james-jsieve.git
#git clone https://github.com/apache/james-jspf.git
#git clone https://github.com/apache/james-mailbox.git
#git clone https://github.com/apache/james-mailet.git
#git clone https://github.com/apache/james-mime4j.git
#git clone https://github.com/apache/james-postage.git
#git clone https://github.com/apache/james-protocols.git
#git clone https://github.com/apache/jena.git
#git clone https://github.com/apache/jmeter.git
#git clone https://github.com/apache/jsecurity.git
#git clone https://github.com/apache/jspwiki.git
#git clone https://github.com/apache/juddi.git
#git clone https://github.com/apache/kalumet.git
#git clone https://github.com/apache/kandula.git
#git clone https://github.com/apache/karaf-cave.git
#git clone https://github.com/apache/karaf-cellar.git
#git clone https://github.com/apache/karaf-webconsole.git
#git clone https://github.com/apache/lenya.git
#git clone https://github.com/apache/log4j-component.git
#git clone https://github.com/apache/log4j-extras.git
#git clone https://github.com/apache/log4j-receivers.git
#git clone https://github.com/apache/log4j-zeroconf.git
#git clone https://github.com/apache/log4j.git
#git clone https://github.com/apache/logging-log4j2.git
#git clone https://github.com/apache/lucene.git
#git clone https://github.com/apache/manifoldcf-integration-solr-3.x.git
#git clone https://github.com/apache/manifoldcf-integration-solr-4.x.git
#git clone https://github.com/apache/manifoldcf.git
#git clone https://github.com/apache/maven-2.git
#git clone https://github.com/apache/maven-ant-tasks.git
#git clone https://github.com/apache/maven-app-engine.git
#git clone https://github.com/apache/maven-archetype.git
#git clone https://github.com/apache/maven-artifact.git
#git clone https://github.com/apache/maven-doxia-sitetools.git
#git clone https://github.com/apache/maven-doxia-tools.git
#git clone https://github.com/apache/maven-doxia.git
#git clone https://github.com/apache/maven-enforcer.git
#git clone https://github.com/apache/maven-indexer.git
#git clone https://github.com/apache/maven-integration-testing.git
#git clone https://github.com/apache/maven-jxr.git
#git clone https://github.com/apache/maven-mercury.git
#git clone https://github.com/apache/maven-plugin-testing.git
#git clone https://github.com/apache/maven-plugin-tools.git
#git clone https://github.com/apache/maven-plugins.git
#git clone https://github.com/apache/maven-release.git
#git clone https://github.com/apache/maven-resources.git
#git clone https://github.com/apache/maven-sandbox.git
#git clone https://github.com/apache/maven-scm.git
#git clone https://github.com/apache/maven-shared.git
#git clone https://github.com/apache/maven-surefire.git
#git clone https://github.com/apache/maven-wagon.git
#git clone https://github.com/apache/maven.git
#git clone https://github.com/apache/mina-sshd.git
#git clone https://github.com/apache/mina.git
#git clone https://github.com/apache/mrunit.git
#git clone https://github.com/apache/myfaces-extcdi.git
#git clone https://github.com/apache/myfaces-extval.git
#git clone https://github.com/apache/myfaces-html5.git
#git clone https://github.com/apache/myfaces-portlet-bridge.git
#git clone https://github.com/apache/myfaces-scripting.git
#git clone https://github.com/apache/myfaces.git
#git clone https://github.com/apache/nuvem.git
#git clone https://github.com/apache/ode-jacob.git
#git clone https://github.com/apache/ode.git
#git clone https://github.com/apache/odftoolkit.git
#git clone https://github.com/apache/ofbiz.git
#git clone https://github.com/apache/oltu.git
#git clone https://github.com/apache/oodt.git
#git clone https://github.com/apache/oozie.git
#git clone https://github.com/apache/openejb.git
#git clone https://github.com/apache/openjpa.git
#git clone https://github.com/apache/opennlp.git
#git clone https://github.com/apache/openwebbeans.git
#git clone https://github.com/apache/pdfbox.git
#git clone https://github.com/apache/photark.git
#git clone https://github.com/apache/pivot.git
#git clone https://github.com/apache/pluto.git
#git clone https://github.com/apache/poi.git
#git clone https://github.com/apache/qpid-jms.git
#git clone https://github.com/apache/qpid-proton.git
#git clone https://github.com/apache/qpid.git
#git clone https://github.com/apache/rampart.git
#git clone https://github.com/apache/rat.git
#git clone https://github.com/apache/rave.git
#git clone https://github.com/apache/redback-components.git
#git clone https://github.com/apache/redback-core.git
#git clone https://github.com/apache/river.git
#git clone https://github.com/apache/roller.git
#git clone https://github.com/apache/sandesha.git
#git clone https://github.com/apache/sanselan.git
#git clone https://github.com/apache/santuario-java.git
#git clone https://github.com/apache/savan.git
#git clone https://github.com/apache/servicemix-archetypes.git
#git clone https://github.com/apache/servicemix-components.git
#git clone https://github.com/apache/servicemix-maven-plugins.git
#git clone https://github.com/apache/servicemix-utils.git
#git clone https://github.com/apache/servicemix3.git
#git clone https://github.com/apache/servicemix4-bundles.git
#git clone https://github.com/apache/servicemix4-features.git
#git clone https://github.com/apache/servicemix4-kernel.git
#git clone https://github.com/apache/servicemix4-nmr.git
#git clone https://github.com/apache/servicemix4-specs.git
#git clone https://github.com/apache/sis.git
#git clone https://github.com/apache/sling.git
#git clone https://github.com/apache/sqoop.git
#git clone https://github.com/apache/stanbol.git
#git clone https://github.com/apache/streams.git
#git clone https://github.com/apache/struts-maven.git
#git clone https://github.com/apache/struts-sandbox.git
#git clone https://github.com/apache/struts1.git
#git clone https://github.com/apache/synapse.git
#git clone https://github.com/apache/syncope.git
#git clone https://github.com/apache/tapestry-5.git
#git clone https://github.com/apache/tapestry3.git
#git clone https://github.com/apache/tapestry4.git
#git clone https://github.com/apache/tapestry5.git
#git clone https://github.com/apache/tez.git
#git clone https://github.com/apache/tiles-autotag.git
#git clone https://github.com/apache/tiles-request.git
#git clone https://github.com/apache/tiles.git
#git clone https://github.com/apache/tomcat-maven-plugin.git
#git clone https://github.com/apache/tomcat55.git
#git clone https://github.com/apache/tomcat60.git
#git clone https://github.com/apache/tomee.git
#git clone https://github.com/apache/tuscany-das.git
#git clone https://github.com/apache/tuscany-sca-1.x.git
#git clone https://github.com/apache/tuscany-sca-2.x.git
#git clone https://github.com/apache/tuscany-sdo.git
#git clone https://github.com/apache/vysper.git
#git clone https://github.com/apache/wave.git
#git clone https://github.com/apache/webservices-axiom.git
#git clone https://github.com/apache/webservices-commons-xmlschema.git
#git clone https://github.com/apache/webservices-neethi.git
#git clone https://github.com/apache/webservices-xmlschema.git
#git clone https://github.com/apache/wink.git
#git clone https://github.com/apache/wss4j.git
#git clone https://github.com/apache/xalan-j.git
#git clone https://github.com/apache/xerces2-j.git
#git clone https://github.com/apache/xml-graphics-commons.git
#git clone https://github.com/apache/xmlbeans.git
